CREATE TABLE IF NOT EXISTS economy_shop_offers (
    id UUID PRIMARY KEY,
    commercial_block_id UUID NOT NULL REFERENCES economy_commercial_blocks(id),
    slot_index INTEGER NOT NULL,
    item_id VARCHAR(255) NOT NULL,
    item_components TEXT NULL,
    item_data_version INTEGER NULL,
    quantity_per_operation INTEGER NOT NULL,
    base_buy_price BIGINT NULL,
    base_sell_price BIGINT NULL,
    minimum_buy_price BIGINT NULL,
    maximum_sell_price BIGINT NULL,
    target_quantity BIGINT NULL,
    purchased_quantity BIGINT NOT NULL,
    comparison_mode VARCHAR(32) NOT NULL,
    pricing_mode VARCHAR(32) NOT NULL,
    demand_level INTEGER NOT NULL,
    supply_level INTEGER NOT NULL,
    quantity_per_price_level BIGINT NULL,
    demand_increase_bps INTEGER NULL,
    supply_decrease_bps INTEGER NULL,
    recovery_levels_per_idle_day INTEGER NOT NULL,
    maximum_demand_level INTEGER NOT NULL,
    maximum_supply_level INTEGER NOT NULL,
    last_player_purchase_date DATE NULL,
    last_player_sale_date DATE NULL,
    is_buy_enabled BOOLEAN NOT NULL,
    is_sell_enabled BOOLEAN NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    version BIGINT NOT NULL,
    CONSTRAINT economy_shop_offers_slot_unique UNIQUE (commercial_block_id, slot_index),
    CONSTRAINT economy_shop_offers_slot_valid CHECK (slot_index >= 0 AND slot_index < 16),
    CONSTRAINT economy_shop_offers_quantity_positive CHECK (quantity_per_operation > 0),
    CONSTRAINT economy_shop_offers_purchased_non_negative CHECK (purchased_quantity >= 0),
    CONSTRAINT economy_shop_offers_demand_non_negative CHECK (demand_level >= 0),
    CONSTRAINT economy_shop_offers_supply_non_negative CHECK (supply_level >= 0),
    CONSTRAINT economy_shop_offers_comparison_valid CHECK (comparison_mode IN ('FULL_COMPONENTS', 'ITEM_ID_ONLY')),
    CONSTRAINT economy_shop_offers_pricing_valid CHECK (pricing_mode IN ('FIXED', 'DYNAMIC', 'MONETARY_GOLD')),
    CONSTRAINT economy_shop_offers_recovery_non_negative CHECK (recovery_levels_per_idle_day >= 0),
    CONSTRAINT economy_shop_offers_max_demand_non_negative CHECK (maximum_demand_level >= 0),
    CONSTRAINT economy_shop_offers_max_supply_non_negative CHECK (maximum_supply_level >= 0),
    CONSTRAINT economy_shop_offers_version_positive CHECK (version > 0)
);

CREATE INDEX IF NOT EXISTS economy_shop_offers_block_idx
    ON economy_shop_offers(commercial_block_id);

