package br.com.economiamod.server.shop;

public enum ShopTransactionResultType {
    COMPLETED,
    OFFER_NOT_FOUND,
    OFFER_DISABLED,
    LINKED_ACCOUNT_REQUIRED,
    INSUFFICIENT_STOCK,
    INSUFFICIENT_PAYMENT,
    INSUFFICIENT_BALANCE,
    INSUFFICIENT_CREDIT,
    INSUFFICIENT_SPACE,
    INVALID_CARD,
    CARD_FUNCTION_NOT_ALLOWED,
    INACTIVE_ACCOUNT,
    ITEM_NOT_ACCEPTED
}
